apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: az-plg-monitoring-ing
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{{{ fill_in_private_dns }}}}
      secretName: {{{ tls-cert-secret }}}
  rules:
    - host: {{{{ fill_in_private_dns }}}}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: loki-grafana
                port:
                  number: 3000
          - pathType: ImplementationSpecific
            path: /grafana/*
            backend:
              service:
                name: loki-grafana
                port:
                  number: 3000
